# Generated by Django 6.0 on 2026-01-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_category_issue_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='helpline_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
